(()=>{
const T=THREE,c=document.getElementById('worldCanvas'),S=new T.Scene(),C=new T.PerspectiveCamera(65,innerWidth/innerHeight,.1,900),R=new T.WebGLRenderer({canvas:c,antialias:true}),W=new T.Group(),B=[];
R.setPixelRatio(Math.min(devicePixelRatio,1.6));R.setSize(innerWidth,innerHeight);R.shadowMap.enabled=true;R.shadowMap.type=T.PCFSoftShadowMap;R.outputEncoding=T.sRGBEncoding;S.fog=new T.Fog(0x071019,65,330);S.add(W);
const D={work:['UNIPOOL HQ','WORK / PRODUCT','UniPool is a university carpooling platform matching students travelling the same route within a +/-1-hour window.','React Native · Expo · TypeScript · FastAPI · Python · MongoDB','https://github.com/um26/UniPool'],analytics:['ANALYTICS LAB','WORK / BACKEND + DATA','A Java 17 CLI backend storing player and game-session records in SQLite through JDBC and analyzing them with SQL.','Java 17 · JDBC · SQLite · SQL','https://github.com/um26/GameScoreAnalytics'],tobs:['OPTIMIZATION LAB','WORK / COMPUTATIONAL MATH','Topology Optimization of Binary Structures using finite-element analysis, sensitivity calculations and sequential integer linear programming.','Python · NGSolve · FEA · Optimization','https://github.com/um26/tobs'],social:['SOCIAL HQ','SOCIAL DISTRICT','GitHub for code, LinkedIn for professional work, and this world for everything in between.','GitHub · LinkedIn','https://github.com/um26'],office:['UM OFFICE','OFFICE DISTRICT','Resume versions, Excel analyses, PowerPoint decks, LaTeX reports, certificates and technical notes.','Resume · Excel · PPT · LaTeX',''],games:['ARCADE DISTRICT','PLAYGROUND','F1 racing, karting, platformers and block-world experiments.','F1 · Kart · Mario · Minecraft · Experiments','games.html'],life:['LIFE DISTRICT','ABOUT','Computational mathematics, quantitative finance, machine learning, software engineering, math-club leadership and Paris.','Mahindra University · CentraleSupélec',''],contact:['CONTACT TERMINAL','CONTACT','For roles, collaborations, project discussions or just talking mathematics and technology.','Email · LinkedIn · GitHub','mailto:umangal2003@gmail.com']};
const spots=[['work',-32,-30],['analytics',-4,-48],['tobs',27,-25],['social',-42,5],['office',8,2],['games',42,-12],['life',-22,38],['contact',31,34]];
let mode='city',player,near=null,keys={},yaw=0,pitch=.18,drag=false,lastX=0,lastY=0,locked=false;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function M(color,rough=.8,metal=.05){return new T.MeshStandardMaterial({color,roughness:rough,metalness:metal})}
function tag(t,col,sub=''){const q=document.createElement('canvas');q.width=900;q.height=180;const x=q.getContext('2d');x.font='900 54px Arial';x.textAlign='center';x.fillStyle='#fff';x.strokeStyle='#050609';x.lineWidth=14;x.strokeText(t,450,72);x.fillText(t,450,72);if(sub){x.font='700 24px Arial';x.fillStyle='#d9e6ef';x.strokeStyle='#050609';x.lineWidth=7;x.strokeText(sub,450,117);x.fillText(sub,450,117)}const tex=new T.CanvasTexture(q);tex.anisotropy=4;const z=new T.Sprite(new T.SpriteMaterial({map:tex,transparent:true,depthTest:false}));z.scale.set(9,1.8,1);z.position.y=10;return z}
function cube(parent,x,y,z,s,mat){const m=new T.Mesh(new T.BoxGeometry(s,s,s),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function blockHouse(x,z,w,d,h,body,roof,key){const g=new T.Group();g.position.set(x,0,z);g.userData.key=key;for(let ix=-w/2;ix<w/2;ix+=1)for(let iz=-d/2;iz<d/2;iz+=1){if(Math.abs(ix)>w/2-1||Math.abs(iz)>d/2-1)cube(g,ix,h/2,iz,1,M(body));}for(let ix=-w/2-1;ix<=w/2;ix++)for(let iz=-d/2-1;iz<=d/2;iz++)cube(g,ix,h+.5,iz,1,M(roof));cube(g,0,1.3,d/2+.2,.9,M(0x5b3b25));for(let y=2;y<h-1;y+=2){[-w/2-.02,w/2+.02].forEach(xx=>cube(g,xx,y,0,.65,M(0x8de8ff,.3,.1)))}g.add(tag(D[key][0],roof,D[key][1]));W.add(g);B.push(g);return g}
function tree(x,z){const g=new T.Group();g.position.set(x,0,z);for(let y=0;y<4;y++)cube(g,0,y+.5,0,1,M(0x79502f));const leaf=M(0x3b8e3b);for(let y=3;y<6;y++)for(let ix=-1;ix<=1;ix++)for(let iz=-1;iz<=1;iz++)if(Math.abs(ix)+Math.abs(iz)<3)cube(g,ix,y,iz,1,leaf);W.add(g)}
function rock(x,z){const g=new T.Group();g.position.set(x,0,z);const mat=M(0x727b86);for(let i=0;i<6;i++){let s=1+Math.random()*1.8;let m=cube(g,(Math.random()-.5)*2,s/2,(Math.random()-.5)*2,s,mat);m.rotation.y=Math.random();}W.add(g)}
function bridge(z){const mat=M(0x7a5634);for(let x=-14;x<=14;x++)cube(W,x,1,z,1,mat)}
function voxelTerrain(){
 S.background=new T.Color(0x79c9ff);S.fog=new T.Fog(0x79c9ff,90,330);S.children.filter(o=>o.isLight).forEach(o=>S.remove(o));S.add(new T.HemisphereLight(0xbfe9ff,0x4c733d,1.9));const sun=new T.DirectionalLight(0xfff4d6,2.4);sun.position.set(-70,100,50);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-110;sun.shadow.camera.right=110;sun.shadow.camera.top=110;sun.shadow.camera.bottom=-110;S.add(sun);
 const grass=M(0x62ad48),dirt=M(0x8b5a35),stone=M(0x777c80),sand=M(0xd6bd70),water=new T.MeshStandardMaterial({color:0x3aa8d8,transparent:true,opacity:.78,roughness:.18});
 const grid=70,step=2;for(let gx=-grid;gx<=grid;gx+=step)for(let gz=-grid;gz<=grid;gz+=step){let h=Math.max(1,Math.floor(3+2*Math.sin(gx*.075)*Math.cos(gz*.06)+1.5*Math.sin((gx+gz)*.12)));if(Math.abs(gx)<16&&Math.abs(gz)<55)h=1;for(let y=0;y<h;y++)cube(W,gx,y*step+1,gz,step,y===h-1?grass:(y<h-2?stone:dirt));}
 const river=new T.Mesh(new T.PlaneGeometry(12,150),water);river.rotation.x=-Math.PI/2;river.position.set(20,.98,0);W.add(river);for(let z=-68;z<70;z+=4){let m=new T.Mesh(new T.BoxGeometry(5,.35,2),M(0x8b6a45));m.position.set(13,1.3,z);m.rotation.y=(z%8?-.18:.18);W.add(m)}
 for(let i=0;i<46;i++){let x=(Math.random()-.5)*125,z=(Math.random()-.5)*125;if(Math.abs(x)<18&&Math.abs(z)<55)continue;tree(x,z)}for(let i=0;i<18;i++){let x=(Math.random()-.5)*125,z=(Math.random()-.5)*125;rock(x,z)}
 // central village square and paths
 const path=M(0xb99668);for(let z=-64;z<=64;z+=2)cube(W,0,2,z,2,path);for(let x=-64;x<=64;x+=2)cube(W,x,2,0,2,path);bridge(0);
 blockHouse(-30,-28,12,10,8,0x9a6b42,0x7b4b31,'work');blockHouse(-4,-48,12,10,7,0xb47745,0x7b5b31,'analytics');blockHouse(28,-25,12,10,9,0x777b86,0x4d5360,'tobs');blockHouse(-42,5,11,10,7,0x6c8c5c,0x563d29,'social');blockHouse(8,2,13,11,8,0xc99d61,0x79512f,'office');blockHouse(42,-12,13,11,7,0x7a5ca8,0x45336c,'games');blockHouse(-22,38,13,11,8,0x5d9b72,0x405d3d,'life');blockHouse(31,34,12,10,7,0xb65a4c,0x66332c,'contact');
 // mountain ring, floating islands and portal
 for(let i=0;i<18;i++){let a=i/18*Math.PI*2,r=82+Math.random()*12,x=Math.cos(a)*r,z=Math.sin(a)*r;for(let j=0;j<7;j++)cube(W,x+(Math.random()-.5)*7,3+j*2,z+(Math.random()-.5)*7,3,M(0x5f6870));}
 for(let i=0;i<6;i++){let g=new T.Group();g.position.set(-45+i*18,25+Math.random()*9,-35-Math.random()*20);for(let j=0;j<8;j++)cube(g,(Math.random()-.5)*6,-j*.35,(Math.random()-.5)*6,2,M(j<2?0x62ad48:0x747a80));W.add(g)}
 const portalMat=new T.MeshBasicMaterial({color:0x7d35ff});for(let i=0;i<8;i++){let p=cube(W,38,2+i%4,35,2,portalMat);p.rotation.y=i*.4}player=new T.Group();const bodyMat=M(0x25364a),skin=M(0xf1bd8d),hair=M(0x16120f);cube(player,0,2,0,2,bodyMat);cube(player,0,4.2,0,2,skin);cube(player,0,5.1,0,1.7,hair);cube(player,-.65,.8,0,.8,bodyMat);cube(player,.65,.8,0,.8,bodyMat);W.add(player);player.position.set(0,3,58);
}
function city(){
 S.background=new T.Color(0x050316);S.fog=new T.Fog(0x050316,75,390);S.children.filter(o=>o.isLight).forEach(o=>S.remove(o));S.add(new T.HemisphereLight(0x6678c8,0x05040a,.75));const a=new T.DirectionalLight(0x5e73ff,.35);a.position.set(-20,40,10);S.add(a);const cyan=new T.PointLight(0x00d9ff,22,100,2),pink=new T.PointLight(0xff1f9a,20,110,2);cyan.position.set(-40,10,-35);pink.position.set(42,10,35);S.add(cyan,pink);
 const ground=new T.Mesh(new T.PlaneGeometry(190,190),M(0x0a0c12,.55,.35));ground.rotation.x=-Math.PI/2;W.add(ground);for(let x=-80;x<=80;x+=20){let road=new T.Mesh(new T.BoxGeometry(8,.1,180),M(0x141923,.65,.3));road.position.set(x,.05,0);W.add(road)}for(let z=-80;z<=80;z+=20){let road=new T.Mesh(new T.BoxGeometry(180,.1,8),M(0x141923,.65,.3));road.position.set(0,.05,z);W.add(road)}
 const neon=[0x00eaff,0xff2e88,0x7d6cff,0xffb52e,0x7dff75];for(let i=0;i<85;i++){let x=(Math.random()-.5)*165,z=(Math.random()-.5)*165,h=7+Math.random()*26,w=4+Math.random()*7,d=4+Math.random()*7;let mat=M([0x101827,0x16111e,0x11151e,0x17131a][i%4],.6,.5);let b=new T.Mesh(new T.BoxGeometry(w,h,d),mat);b.position.set(x,h/2,z);b.castShadow=true;W.add(b);for(let y=3;y<h;y+=3){let line=new T.Mesh(new T.BoxGeometry(w+.03,.16,.06),new T.MeshBasicMaterial({color:neon[i%neon.length]}));line.position.set(x,y,z-d/2-.03);W.add(line)}}
 const plaza=new T.Mesh(new T.CircleGeometry(18,64),new T.MeshStandardMaterial({color:0x171b28,metalness:.7,roughness:.25}));plaza.rotation.x=-Math.PI/2;plaza.position.y=.08;W.add(plaza);spots.forEach((s,i)=>{let [key,x,z]=s,g=new T.Group();g.position.set(x,0,z);g.userData.key=key;let h=10+((i*7)%12),w=8+(i%3)*2;let b=new T.Mesh(new T.BoxGeometry(w,h,7),M(0x121824,.55,.5));b.position.y=h/2;g.add(b);let neonMat=new T.MeshBasicMaterial({color:[0x00eaff,0xff2e88,0x8b6cff,0x4e9cff,0xffbd3e,0x72ff75,0xb878ff,0xff6c6c][i]});let sign=new T.Mesh(new T.BoxGeometry(w+.8,1.2,.18),neonMat);sign.position.set(0,h*.72,-3.62);g.add(sign);g.add(tag(D[key][0],neonMat.color.getHex(),D[key][1]));W.add(g);B.push(g)});
 player=new T.Group();const body=M(0x10131a,.4,.3),hood=M(0x202634,.4,.25),skin=M(0xd89469);let torso=new T.Mesh(new T.BoxGeometry(1.6,2.2,1),hood);torso.position.y=2;player.add(torso);let head=new T.Mesh(new T.BoxGeometry(1.25,1.25,1.25),skin);head.position.y=3.8;player.add(head);let hair=new T.Mesh(new T.BoxGeometry(1.35,.55,1.3),body);hair.position.y=4.45;player.add(hair);[-.55,.55].forEach(x=>{let leg=new T.Mesh(new T.BoxGeometry(.55,1.5,.7),body);leg.position.set(x,.65,0);player.add(leg)});W.add(player);player.position.set(0,0,58)
}
function build(){while(W.children.length)W.remove(W.children[0]);B.length=0;mode==='block'?voxelTerrain():city();C.position.set(0,7,69);yaw=0;pitch=.18}
function open(k){const d=D[k];let html='<span class="kicker">'+d[1]+'</span><h2>'+d[0]+'</h2><p>'+d[2]+'</p><div class="data"><div><b>STACK / FORMAT</b><span>'+d[3]+'</span></div><div><b>DISCOVERED IN</b><span>'+('city'===mode?'Neon City':'Block World')+'</span></div></div>';if(d[4])html+='<a class="panel-link" href="'+d[4]+'" target="_blank" rel="noreferrer">OPEN PROJECT ↗</a>';document.getElementById('panelContent').innerHTML=html;document.getElementById('panel').classList.add('open')}
function set(m){mode=m;document.body.dataset.mode=m;document.querySelectorAll('.mode button').forEach(x=>x.classList.toggle('active',x.dataset.mode===m));localStorage.setItem('um-world-mode',m);build()}
document.querySelectorAll('.mode button').forEach(x=>x.onclick=()=>set(x.dataset.mode));document.getElementById('closePanel').onclick=()=>document.getElementById('panel').classList.remove('open');
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=1;if(e.code==='Space'&&mode==='block')keys.jump=1;if(e.key==='e'&&near)open(near.userData.key);if(e.key==='Escape'){document.getElementById('panel').classList.remove('open');if(document.pointerLockElement===c)document.exitPointerLock()}});addEventListener('keyup',e=>{keys[e.key.toLowerCase()]=0;if(e.code==='Space')keys.jump=0});
c.addEventListener('click',()=>{if(innerWidth>760&&!document.pointerLockElement)c.requestPointerLock?.()});addEventListener('pointerlockchange',()=>locked=document.pointerLockElement===c);
addEventListener('pointermove',e=>{if(locked){yaw-=e.movementX*.0025;pitch-=e.movementY*.0022;pitch=clamp(pitch,-.9,1.0)}else if(drag){yaw-=(e.clientX-lastX)*.004;pitch-=(e.clientY-lastY)*.003;pitch=clamp(pitch,-.9,1.0);lastX=e.clientX;lastY=e.clientY}});
c.addEventListener('pointerdown',e=>{if(!locked){drag=true;lastX=e.clientX;lastY=e.clientY}});addEventListener('pointerup',()=>drag=false);
addEventListener('wheel',e=>{if(e.shiftKey||Math.abs(e.deltaX)>Math.abs(e.deltaY)){yaw-=e.deltaX*.0025||e.deltaY*.001}else{pitch-=e.deltaY*.0015}pitch=clamp(pitch,-.9,1.0)},{passive:true});
addEventListener('resize',()=>{C.aspect=innerWidth/innerHeight;C.updateProjectionMatrix();R.setSize(innerWidth,innerHeight)});
set(localStorage.getItem('um-world-mode')==='block'?'block':'city');let clock=new T.Clock(),vy=0;
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.05);let ix=0,iz=0;if(keys.w||keys.arrowup)iz=-1;if(keys.s||keys.arrowdown)iz=1;if(keys.a||keys.arrowleft)ix=-1;if(keys.d||keys.arrowright)ix=1;if(ix||iz){let l=Math.hypot(ix,iz);ix/=l;iz/=l;let cs=Math.cos(yaw),sn=Math.sin(yaw),mx=ix*cs-iz*sn,mz=ix*sn+iz*cs;let speed=keys.shift?12:7;player.position.x+=mx*speed*dt;player.position.z+=mz*speed*dt;player.rotation.y=Math.atan2(mx,mz)}if(mode==='block'){if(keys.jump&&player.position.y<=3.01)vy=10;vy-=24*dt;player.position.y+=vy*dt;if(player.position.y<3){player.position.y=3;vy=0}}else player.position.y=0;player.position.x=clamp(player.position.x,-76,76);player.position.z=clamp(player.position.z,-76,76);
 const dist=mode==='block'?11.5:9.5;const target=new T.Vector3(player.position.x,player.position.y+(mode==='block'?2.9:2.3),player.position.z);const dir=new T.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch));const camTarget=target.clone().add(dir.clone().multiplyScalar(dist));camTarget.y+=2.2;C.position.lerp(camTarget,.12);C.lookAt(target.clone().add(dir.multiplyScalar(20)));
 near=null;let best=mode==='block'?7:6;B.forEach(b=>{let q=player.position.distanceTo(b.position);if(q<best){best=q;near=b}});const pr=document.getElementById('prompt');if(near){document.getElementById('promptName').textContent=D[near.userData.key][0];pr.classList.add('show')}else pr.classList.remove('show');
 if(mode==='city'){player.rotation.y=yaw;S.fog.density=.002}else S.fog.density=.002;R.render(S,C)}loop();
})();