(()=>{const T=THREE,canvas=document.getElementById('world'),scene=new T.Scene(),camera=new T.PerspectiveCamera(68,innerWidth/innerHeight,.1,1800),renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'}),world=new T.Group(),loader=new T.GLTFLoader(),clock=new T.Clock(),keys={},assets={},hotspots=[];renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputEncoding=T.sRGBEncoding;scene.add(world);let mode=localStorage.getItem('um-world-mode')||'city',yaw=0,pitch=-.08,locked=false,near=null,player,particles,mouseX=0,mouseY=0;
const DATA={work:['UNIPOOL HQ','WORK / PRODUCT','A real university carpooling platform: students create pools, match routes and time windows, view matches and receive notifications.','React Native · Expo · TypeScript · FastAPI · Python · MongoDB','https://github.com/um26/UniPool'],analytics:['ANALYTICS LAB','WORK / BACKEND + DATA','Java 17 CLI backend with JDBC and SQLite, DAO separation and SQL analytics over player and game-session data.','Java 17 · JDBC · SQLite · SQL','https://github.com/um26/GameScoreAnalytics'],tobs:['OPTIMIZATION LAB','WORK / COMPUTATIONAL MATH','Binary topology optimization using finite-element analysis, sensitivity calculations and sequential integer-linear programming.','Python · NGSolve · FEA · Optimization','https://github.com/um26/tobs'],social:['SOCIAL HQ','SOCIAL / PRESENCE','The professional layer: GitHub repositories, LinkedIn work, achievements, Math Club leadership and public writing.','GitHub · LinkedIn · Math Club','https://github.com/um26'],office:['UM OFFICE','DOCUMENTS / WORKSPACE','Resume versions, Excel analyses, PowerPoint decks, LaTeX reports, certificates and technical notes.','Resume · Excel · PPT · LaTeX',''],games:['ARCADE DISTRICT','PLAY / EXPERIMENTS','F1, racing, games and interactive experiments. This is where the portfolio stops being a portfolio.','F1 · Kart · Games · Experiments','games.html'],life:['LIFE DISTRICT','ABOUT / JOURNEY','Computational mathematics, quantitative finance, machine learning, software engineering, leadership and life between India and Paris.','Math · Quant · AI · Engineering',''],contact:['CONTACT TERMINAL','CONTACT / CONNECT','For roles, collaborations, project discussions or just talking mathematics and technology.','Email · LinkedIn · GitHub','mailto:umangal2003@gmail.com']};
const CITY_ASSETS={small:'https://raw.githubusercontent.com/anshaneja5/skyline-run/main/public/assets/models/b_small.glb',medium:'https://raw.githubusercontent.com/anshaneja5/skyline-run/main/public/assets/models/b_medium.glb',large:'https://raw.githubusercontent.com/anshaneja5/skyline-run/main/public/assets/models/b_large.glb',ac:'https://raw.githubusercontent.com/anshaneja5/skyline-run/main/public/assets/models/prop_ac.glb'};const BLOCK_ASSETS={house:'https://cdn.jsdelivr.net/gh/syuhei176/ai-game-assets@v1/models/environment/building_house.glb',tree:'https://cdn.jsdelivr.net/gh/syuhei176/ai-game-assets@v1/models/environment/tree_oak.glb',pine:'https://cdn.jsdelivr.net/gh/syuhei176/ai-game-assets@v1/models/environment/tree_pine.glb',rock:'https://cdn.jsdelivr.net/gh/syuhei176/ai-game-assets@v1/models/environment/rock_large.glb'};
const palCity=[0x00eaff,0xff3b86,0x8b5cff,0xffd166,0x36f1cd,0x7b8cff,0xff6b4a,0xb8ff3d];const palBlock=[0xe8a44c,0x5aa9e6,0xe76f51,0x73b96b,0xc58cff,0xf2cf66,0x6ec8c5,0xdf6c9c];
function mat(c,rough=.65,metal=.1,em=0){return new T.MeshStandardMaterial({color:c,roughness:rough,metalness:metal,emissive:em?c:0,emissiveIntensity:em})}function clear(){while(world.children.length)world.remove(world.children[0]);hotspots.length=0;particles=null}function box(w,h,d,c,x,y,z,m=.2){let q=new T.Mesh(new T.BoxGeometry(w,h,d),mat(c,.55,m));q.position.set(x,y,z);q.castShadow=q.receiveShadow=true;world.add(q);return q}
function label(text,color,y=10,scale=1){const cv=document.createElement('canvas');cv.width=1024;cv.height=180;const x=cv.getContext('2d');x.clearRect(0,0,1024,180);x.font='900 72px Arial';x.textAlign='center';x.textBaseline='middle';x.strokeStyle='#02050a';x.lineWidth=22;x.shadowColor='#000';x.shadowBlur=16;x.strokeText(text,512,90);x.fillStyle='#fff';x.fillText(text,512,90);const s=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(cv),transparent:true,depthTest:false,depthWrite:false}));s.scale.set(13*scale,2.3*scale,1);s.position.y=y;s.renderOrder=50;return s}
function neonLine(x1,z1,x2,z2,c,y=.04,w=.07){const g=new T.BufferGeometry().setFromPoints([new T.Vector3(x1,y,z1),new T.Vector3(x2,y,z2)]);const l=new T.Line(g,new T.LineBasicMaterial({color:c,transparent:true,opacity:.85}));world.add(l);return l}
function roadCity(x,z,w,d,rot=0){const r=box(w,.18,d,0x11161e,x,.05,z,.8);r.rotation.y=rot;const count=Math.floor(Math.max(w,d)/6);for(let i=-count;i<=count;i++){let p=box(.09,.025,2.4,0xe7edf5,x,.16,z+i*6,.05);p.rotation.y=rot}return r}
function addBillboard(x,y,z,text,c){let g=new T.Group();g.position.set(x,y,z);let panel=box(5.8,2.5,.12,0x090d15,x,y,z,.5);panel.material.emissive=new T.Color(c);panel.material.emissiveIntensity=.12;let l=label(text,c,0,.55);l.position.set(0,.02,.09);g.add(l);g.add(panel);world.add(g);return g}
function lightsCity(){scene.background=new T.Color(0x03050b);scene.fog=new T.FogExp2(0x050812,.0048);scene.add(new T.HemisphereLight(0x48627e,0x020106,.7));const sun=new T.DirectionalLight(0x91b8ff,.7);sun.position.set(-80,110,30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);world.add(sun);[[0x00eaff,0,18,0,120],[0xff287d,55,22,-50,130],[0x7c4dff,-70,16,55,100]].forEach(a=>{let p=new T.PointLight(a[0],35,a[4],2);p.position.set(a[1],a[2],a[3]);world.add(p)});}
function loadAsset(key,url){return new Promise(res=>loader.load(url,g=>{assets[key]=g.scene;res(g.scene)},undefined,()=>res(null)))}
function cloneAsset(key,x,z,s,rot=0,accent=0x00eaff){let base=assets[key];if(!base)return null;let g=base.clone(true);g.position.set(x,0,z);g.rotation.y=rot;g.scale.setScalar(s);g.traverse(o=>{if(o.isMesh){o.castShadow=o.receiveShadow=true;if(o.material){o.material=o.material.clone();if(mode==='city'){o.material.roughness=Math.min(.8,o.material.roughness??.6);o.material.metalness=Math.max(.18,o.material.metalness??.1)}}}});world.add(g);return g}
function addWindowBands(g,color){const b=new T.Box3().setFromObject(g),size=b.getSize(new T.Vector3()),center=b.getCenter(new T.Vector3());for(let side of [-1,1])for(let y=center.y+2;y<b.max.y-1;y+=3.1){let q=new T.Mesh(new T.BoxGeometry(Math.max(2,size.x*.72),.13,.035),new T.MeshBasicMaterial({color,transparent:true,opacity:.48}));q.position.set(center.x,y,center.z+side*(size.z/2+.04));world.add(q)}}
function city(){lightsCity();const ground=box(190,.5,190,0x080c13,0,-.3,0,.8);ground.receiveShadow=true;roadCity(0,0,15,190);roadCity(0,0,190,15,Math.PI/2);roadCity(-42,0,8,190);roadCity(42,0,8,190);roadCity(0,-42,8,190,Math.PI/2);roadCity(0,42,8,190,Math.PI/2);
for(let i=-5;i<=5;i++){neonLine(i*7,-95,i*7,95,palCity[(i+8)%palCity.length],.17,.04);neonLine(-95,i*7,95,i*7,palCity[(i+10)%palCity.length],.17,.04)}
const spots=[['work',-28,-27,1.5],['analytics',27,-27,1.65],['tobs',-28,28,1.45],['social',28,28,1.45],['office',0,24,1.55],['games',0,-55,1.5],['life',-55,-52,1.35],['contact',55,-52,1.3]];
spots.forEach((s,i)=>{const g=cloneAsset(i%3===0?'large':i%3===1?'medium':'small',s[1],s[2],s[3],(i%4)*.45,palCity[i]);if(!g)return;addWindowBands(g,palCity[i]);const b=new T.Box3().setFromObject(g);let h=b.max.y;const l=label(DATA[s[0]][0],palCity[i],h+4);l.position.x=0;l.position.z=0;g.add(l);const ring=new T.Mesh(new T.TorusGeometry(Math.max(5,(b.max.x-b.min.x)*.45),.09,8,80),new T.MeshBasicMaterial({color:palCity[i],transparent:true,opacity:.65}));ring.rotation.x=Math.PI/2;ring.position.y=h*.45;g.add(ring);g.userData.key=s[0];hotspots.push(g)});
for(let i=0;i<34;i++){let x=(Math.random()-.5)*180,z=(Math.random()-.5)*180;if(Math.abs(x)<12||Math.abs(z)<12)continue;let key=i%3?'medium':'small',g=cloneAsset(key,x,z,.65+Math.random()*.55,Math.random()*6.28,palCity[i%palCity.length]);if(g)addWindowBands(g,palCity[(i+3)%palCity.length])}
for(let i=0;i<16;i++){let x=(Math.random()-.5)*150,z=(Math.random()-.5)*150;addBillboard(x,12+Math.random()*18,z,['QUANT','BUILD','CREATE','MATH','AI','UM / 26'][i%6],palCity[i%palCity.length])}
// elevated transit rails
for(let r=-1;r<=1;r++){let rail=box(1.1,1.2,175,0x1b2230,r*26,6,0,.8);for(let z=-82;z<82;z+=8){let beam=box(5,.12,.18,palCity[(r+2)%palCity.length],r*26,6.7,z,.2);world.add(beam)}}
// holographic sky pillars
for(let i=0;i<9;i++){let q=new T.Mesh(new T.CylinderGeometry(.08,.08,30,8),new T.MeshBasicMaterial({color:palCity[i%palCity.length],transparent:true,opacity:.22,blending:T.AdditiveBlending}));q.position.set((i-4)*22,15,(i%3-1)*55);world.add(q)}}
function block(){scene.background=new T.Color(0x8dc7ef);scene.fog=new T.Fog(0x8dc7ef,120,420);scene.add(new T.HemisphereLight(0xcff4ff,0x5f7042,1.55));let sun=new T.DirectionalLight(0xfff2d4,2.1);sun.position.set(-80,130,50);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);world.add(sun);box(220,1,220,0x4d8d49,0,-.55,0,.05);for(let x=-100;x<=100;x+=10)for(let z=-100;z<=100;z+=10){if(Math.random()<.13)box(10,.25,10,0x6fae58,x,.05,z,0)}
function path(x,z,w,d){box(w,.18,d,0x807e73,x,.12,z,.02)}path(0,0,14,210);path(0,0,210,14);path(-48,0,8,210);path(48,0,8,210);path(0,-48,8,210);path(0,48,8,210);for(let i=0;i<8;i++){let q=box(16,.3,4,0x4a8fca,-58+i*16,.2,-2,.05);q.rotation.y=Math.sin(i)*.02}
const spots=[['work',-28,-27,1.15],['analytics',28,-27,1.2],['tobs',-28,28,1.1],['social',28,28,1.1],['office',0,28,1.15],['games',0,-58,1.1],['life',-58,-55,1],['contact',58,-55,1]];spots.forEach((s,i)=>{let g=cloneAsset('house',s[1],s[2],s[3],(i%2)*Math.PI,palBlock[i]);if(!g)return;let b=new T.Box3().setFromObject(g),h=b.max.y;g.userData.key=s[0];g.add(label(DATA[s[0]][0],palBlock[i],h+3));hotspots.push(g)});
for(let i=0;i<70;i++){let x=(Math.random()-.5)*190,z=(Math.random()-.5)*190;if(Math.abs(x)<12||Math.abs(z)<12)continue;let key=i%4===0?'pine':i%3===0?'tree':'rock',g=cloneAsset(key,x,z,.65+Math.random()*.75,Math.random()*6.28,palBlock[i%palBlock.length]);if(g)g.rotation.y=Math.random()*6.28}
// voxel landmarks, bridges and towers
for(let i=0;i<14;i++){let x=(i%7-3)*15,z=(Math.floor(i/7)*2-1)*22;for(let y=0;y<5+(i%3)*2;y++)box(3,3,3,palBlock[i%palBlock.length],x,1.5+y*3,z,.05);box(4,.5,4,0x7c583c,x,17,z,.05)}for(let i=0;i<30;i++){let q=box(1,1,1,palBlock[i%palBlock.length],(Math.random()-.5)*100,4+Math.random()*10,(Math.random()-.5)*100,.1);q.rotation.set(Math.random(),Math.random(),Math.random())}
// block clouds
for(let i=0;i<18;i++){let g=new T.Group();for(let j=0;j<4;j++){let q=box(4+Math.random()*3,2.5,3,0xffffff,0,0,0,.02);q.position.set((j-1.5)*3,Math.random()*1.5,Math.random()*2);g.add(q)}g.position.set((Math.random()-.5)*190,30+Math.random()*20,(Math.random()-.5)*160);world.add(g)}}
async function build(){clear();if(mode==='city'){await Promise.all(Object.entries(CITY_ASSETS).map(([k,u])=>loadAsset(k,u)));city()}else{await Promise.all(Object.entries(BLOCK_ASSETS).map(([k,u])=>loadAsset(k,u)));block()}player=new T.Group();let body=box(1.05,1.7,.7,mode==='city'?0x00eaff:0x3f7ee8,0,0,0,.25);body.position.set(0,1.15,0);let head=box(.72,.72,.72,mode==='city'?0xdce7ef:0xf0c7a5,0,0,0,.05);head.position.set(0,2.35,0);player.add(body,head);world.add(player);player.position.set(0,0,70);document.body.classList.toggle('mode-block',mode==='block');document.querySelectorAll('.switch button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));document.getElementById('modeTag').textContent=mode==='city'?'NEON CITY / NIGHT':'BLOCK WORLD / DAY';document.getElementById('tip').textContent=innerWidth<760?'TOUCH / WASD / DRAG TO EXPLORE':'CLICK TO CAPTURE MOUSE · WASD TO MOVE';}
function interact(k){const d=DATA[k];document.getElementById('panelKicker').textContent=d[1];document.getElementById('panelTitle').textContent=d[0];document.getElementById('panelText').textContent=d[2];document.getElementById('panelStack').textContent=d[3];document.getElementById('panelSector').textContent=mode==='city'?'NEON CITY':'BLOCK WORLD';const a=document.getElementById('panelLink');a.style.display=d[4]?'inline-flex':'none';if(d[4])a.href=d[4];document.getElementById('panel').classList.add('open')}
function updateNear(){near=null;let best=18;for(const g of hotspots){const p=g.getWorldPosition(new T.Vector3());const d=p.distanceTo(player.position);if(d<best){best=d;near=g}}const el=document.getElementById('interact');if(near){el.classList.add('show');document.getElementById('interactName').textContent=DATA[near.userData.key][0];document.getElementById('loc').textContent=DATA[near.userData.key][0]}else{el.classList.remove('show');document.getElementById('loc').textContent=mode==='city'?'CITY CENTER':'BLOCK VILLAGE'}}
function setMode(m){mode=m;localStorage.setItem('um-world-mode',m);build()}document.querySelectorAll('.switch button').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.getElementById('close').onclick=()=>document.getElementById('panel').classList.remove('open');addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=1;if(e.key==='e'&&near)interact(near.userData.key);if(e.key==='Escape'){document.exitPointerLock?.();document.getElementById('panel').classList.remove('open')}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);canvas.addEventListener('click',()=>{if(innerWidth>760)canvas.requestPointerLock?.()});addEventListener('pointerlockchange',()=>{locked=document.pointerLockElement===canvas;document.getElementById('tip').style.opacity=locked?'.25':'1'});addEventListener('mousemove',e=>{if(locked){yaw-=e.movementX*.0025;pitch-=e.movementY*.0022;pitch=Math.max(-1.25,Math.min(.72,pitch))}});let drag=false,lx=0,ly=0;canvas.addEventListener('pointerdown',e=>{if(!locked){drag=true;lx=e.clientX;ly=e.clientY}});addEventListener('pointerup',()=>drag=false);addEventListener('pointermove',e=>{if(drag&&!locked){yaw-=(e.clientX-lx)*.004;pitch-=(e.clientY-ly)*.003;pitch=Math.max(-1.25,Math.min(.72,pitch));lx=e.clientX;ly=e.clientY}});addEventListener('wheel',e=>{pitch-=e.deltaY*.0004;pitch=Math.max(-1.25,Math.min(.72,pitch))},{passive:true});
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.05);let x=0,z=0;if(keys.w||keys.arrowup)z=-1;if(keys.s||keys.arrowdown)z=1;if(keys.a||keys.arrowleft)x=-1;if(keys.d||keys.arrowright)x=1;if(x||z){let l=Math.hypot(x,z);x/=l;z/=l;const cs=Math.cos(yaw),sn=Math.sin(yaw),mx=x*cs-z*sn,mz=x*sn+z*cs;player.position.x+=mx*(mode==='city'?13:10)*dt;player.position.z+=mz*(mode==='city'?13:10)*dt;player.rotation.y=Math.atan2(mx,mz)}player.position.x=Math.max(-88,Math.min(88,player.position.x));player.position.z=Math.max(-88,Math.min(88,player.position.z));const target=new T.Vector3(player.position.x,1.7,player.position.z),dist=mode==='city'?12:11,cp=Math.cos(pitch),sp=Math.sin(pitch);const off=new T.Vector3(Math.sin(yaw)*cp*dist,5+sp*dist,Math.cos(yaw)*cp*dist);camera.position.lerp(target.clone().add(off),.1);camera.lookAt(target);world.rotation.y=0;updateNear();if(mode==='city'){world.traverse(o=>{if(o.isMesh&&o.material?.emissiveIntensity&&o.material.emissive){o.material.emissiveIntensity=.65+Math.sin(clock.elapsedTime*2+o.id)*.18}})}renderer.render(scene,camera)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});build().then(loop)})();